version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - run: echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          no_output_timeout: 1200s
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
